name: First workflow
on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: multi command
        run: |
          node -v
          npm -v
  parallel-job-macos:
    runs-on: macos-latest
    steps:
      - name: view sw version
        run: sw_vers
  dependent-job:
    runs-on: windows-latest
    needs: run-shell-commands
    steps:
      - name: echo a string
        run: Write-Output "Window String"
      - name: Error step
        run: doesnotexits
