name: Manual workflow
on: 
  workflow_dispatch:
    inputs:
      string:
        description: A string input
        type: string
        required: true
        default: "Default value"
      number:
        description: A number input
        default: 4
        type: number
      option:
        description: "An option input"
        required: true
        default: "option 3"
        type: choice
        options:
          - option 1
          - option 2
          - option 3
      boolean:
        description: A boolean option
        required: false
        type: boolean
      environment:
        description: "Environment"
        type: environment
        required: true

jobs:
  log-info:
    runs-on: ubuntu-latest
    steps:
      - run: echo $GITHUB_REF
      - run: |
          echo "Boolean: ${{ inputs.boolean }}"
          echo "String: ${{ inputs.string }}"
          echo "Environment: ${{ inputs.environment }}"
          echo "Number: ${{ inputs.number }}"
          echo "Option: ${{ inputs.option }}"