name: Working Dir & Shell
on: [push]
jobs:
  display-wd-info:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Display working dir and list files
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
      - name: change working directory
        working-directory: /home/runner
        run: pwd
  display-wd-info-windows:
    runs-on: windows-latest
    defaults:
        run:
          shell: pwsh
    steps:
      - name: Display working dir and list files
        run: |
           Get-Location
           dir
           echo $env:GITHUB_SHA
           echo $env:GITHUB_REPOSITORY
           echo $env:GITHUB_WORKSPACE
      - name: Python shell
        shell: python
        run: |
          import platform
          print(platform.processor())
